config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/help", to: "static_pages#help"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/views/static_pages/about.slim
- provide(:title, (t ".title"))
h1
  = t ".title"
p
  = t ".description_html",
  link_tutorial: "https://www.railstutorial.org/",
  link_learn_enough: "https://www.learnenough.com/",
  link_book: "https://www.railstutorial.org/book",
  link_screencast: "https://screencasts.railstutorial.org/",
  link_rails: "https://rubyonrails.org/"

app/views/static_pages/contact.slim
- provide(:title, (t ".title"))
h1
  = t ".title"
p
  = t ".description_html", link_contact: "https://www.railstutorial.org/contact"

app/views/static_pages/help.slim
- provide(:title, (t ".title"))
h1
  = t ".title"
p
  = t ".description_html",
  link_help: "https://www.railstutorial.org/help",
  link_book: "https://www.railstutorial.org/book"

app/views/static_pages/home.slim
.center.jumbotron
  - provide(:title, (t ".title"))
  h1
    = t ".app_welcome"
  p
    = t ".description_html", link_tutorial: "https://www.railstutorial.org/"
  = link_to (t ".signup_now"), new_user_path, class: "btn btn-lg btn-primary"
= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"), "https://rubyonrails.org/"