config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/help", to: "static_pages#help"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
  end
end

app/views/layouts/_footer.slim
footer.footer
  small
    = t "layouts.footer.description_html",
    link_rails: "https://www.railstutorial.org/",
    link_author: "https://www.michaelhartl.com/"
  nav
    ul
      li
        = link_to (t ".about"), about_path
      li
        = link_to (t ".contact"), contact_path
      li
        a[href="https://news.railstutorial.org/"]
          = t ".news"

app/views/layouts/_header.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container.header-container
    = link_to (t "layouts.header.app_name"), root_path, id: "logo"
    nav
      .navbar-header
        button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"]
          span.sr-only
            | Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
      ul#bs-example-navbar-collapse-1.nav.navbar-nav.navbar-right.collapse.navbar-collapse
        li
          = link_to (t ".home"), root_path
        li
          = link_to (t ".help"), help_path
        - if logged_in?
          li
            = link_to (t ".users"), users_path
          li.dropdown
            a.dropdown-toggle[href="#" data-toggle="dropdown"]
              = (t ".account")
              b.caret
            ul.dropdown-menu
              li
                = link_to (t ".profile"), current_user
              li
                = link_to (t ".settings"), edit_user_path(current_user)
              li.divider
              li
                = link_to (t ".logout"), logout_path, method: :delete
        - else
          li
            = link_to (t ".login"), login_path

app/views/layouts/application.slim
doctype html
html
  head
    title
      = yield(:title)
      | |
      =  t ".title_description"
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    script[src="https://code.jquery.com/jquery-3.5.1.min.js"]
    script[src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"]
  body
    = render "layouts/header"
    .container
      - flash.each do |message_type, message|
        .alert(class="alert-#{message_type}")
          = message
    = yield
    = render "layouts/footer"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"